<?php

namespace App\Filament\Resources\CategoryResource\Pages;

use Yemenpoint\FilamentTree\TreePage;
use App\Filament\Resources\CategoryResource;
use App\Models\Category;

class TreeCategory extends TreePage
{
    protected static string $resource = CategoryResource::class;

    //protected static string $view = 'filament.resources.category-resource.pages.tree-category';

    public function getItems(): array
    {
        return Category::with("children")->whereNull("parent_id")->orderBy("order")->get()->toArray();
    }

    public function getMaxDepth(): int
    {
        return parent::getMaxDepth(); // TODO: Change the autogenerated stub
    }

    public function isDisabled(): bool
    {
        return parent::isDisabled(); // TODO: Change the autogenerated stub
    }
}